export type CallingCode = { iso2: string; country: string; code: string };

// Source: Consolidated from ITU E.164 allocations and common references.
// Note: Some territories share calling codes (e.g., +1 NANP countries).
export const CALLING_CODES: CallingCode[] = [
  { iso2: 'AF', country: 'Afghanistan', code: '+93' },
  { iso2: 'AL', country: 'Albania', code: '+355' },
  { iso2: 'DZ', country: 'Algeria', code: '+213' },
  { iso2: 'AD', country: 'Andorra', code: '+376' },
  { iso2: 'AO', country: 'Angola', code: '+244' },
  { iso2: 'AG', country: 'Antigua and Barbuda', code: '+1' },
  { iso2: 'AR', country: 'Argentina', code: '+54' },
  { iso2: 'AM', country: 'Armenia', code: '+374' },
  { iso2: 'AU', country: 'Australia', code: '+61' },
  { iso2: 'AT', country: 'Austria', code: '+43' },
  { iso2: 'AZ', country: 'Azerbaijan', code: '+994' },
  { iso2: 'BS', country: 'Bahamas', code: '+1' },
  { iso2: 'BH', country: 'Bahrain', code: '+973' },
  { iso2: 'BD', country: 'Bangladesh', code: '+880' },
  { iso2: 'BB', country: 'Barbados', code: '+1' },
  { iso2: 'BY', country: 'Belarus', code: '+375' },
  { iso2: 'BE', country: 'Belgium', code: '+32' },
  { iso2: 'BZ', country: 'Belize', code: '+501' },
  { iso2: 'BJ', country: 'Benin', code: '+229' },
  { iso2: 'BT', country: 'Bhutan', code: '+975' },
  { iso2: 'BO', country: 'Bolivia', code: '+591' },
  { iso2: 'BA', country: 'Bosnia and Herzegovina', code: '+387' },
  { iso2: 'BW', country: 'Botswana', code: '+267' },
  { iso2: 'BR', country: 'Brazil', code: '+55' },
  { iso2: 'BN', country: 'Brunei', code: '+673' },
  { iso2: 'BG', country: 'Bulgaria', code: '+359' },
  { iso2: 'BF', country: 'Burkina Faso', code: '+226' },
  { iso2: 'BI', country: 'Burundi', code: '+257' },
  { iso2: 'KH', country: 'Cambodia', code: '+855' },
  { iso2: 'CM', country: 'Cameroon', code: '+237' },
  { iso2: 'CA', country: 'Canada', code: '+1' },
  { iso2: 'CV', country: 'Cape Verde', code: '+238' },
  { iso2: 'CF', country: 'Central African Republic', code: '+236' },
  { iso2: 'TD', country: 'Chad', code: '+235' },
  { iso2: 'CL', country: 'Chile', code: '+56' },
  { iso2: 'CN', country: 'China', code: '+86' },
  { iso2: 'CO', country: 'Colombia', code: '+57' },
  { iso2: 'KM', country: 'Comoros', code: '+269' },
  { iso2: 'CG', country: 'Congo', code: '+242' },
  { iso2: 'CD', country: 'Congo, Dem. Rep.', code: '+243' },
  { iso2: 'CR', country: 'Costa Rica', code: '+506' },
  { iso2: 'CI', country: 'Côte d’Ivoire', code: '+225' },
  { iso2: 'HR', country: 'Croatia', code: '+385' },
  { iso2: 'CU', country: 'Cuba', code: '+53' },
  { iso2: 'CY', country: 'Cyprus', code: '+357' },
  { iso2: 'CZ', country: 'Czechia', code: '+420' },
  { iso2: 'DK', country: 'Denmark', code: '+45' },
  { iso2: 'DJ', country: 'Djibouti', code: '+253' },
  { iso2: 'DM', country: 'Dominica', code: '+1' },
  { iso2: 'DO', country: 'Dominican Republic', code: '+1' },
  { iso2: 'EC', country: 'Ecuador', code: '+593' },
  { iso2: 'EG', country: 'Egypt', code: '+20' },
  { iso2: 'SV', country: 'El Salvador', code: '+503' },
  { iso2: 'GQ', country: 'Equatorial Guinea', code: '+240' },
  { iso2: 'ER', country: 'Eritrea', code: '+291' },
  { iso2: 'EE', country: 'Estonia', code: '+372' },
  { iso2: 'SZ', country: 'Eswatini', code: '+268' },
  { iso2: 'ET', country: 'Ethiopia', code: '+251' },
  { iso2: 'FJ', country: 'Fiji', code: '+679' },
  { iso2: 'FI', country: 'Finland', code: '+358' },
  { iso2: 'FR', country: 'France', code: '+33' },
  { iso2: 'GA', country: 'Gabon', code: '+241' },
  { iso2: 'GM', country: 'Gambia', code: '+220' },
  { iso2: 'GE', country: 'Georgia', code: '+995' },
  { iso2: 'DE', country: 'Germany', code: '+49' },
  { iso2: 'GH', country: 'Ghana', code: '+233' },
  { iso2: 'GR', country: 'Greece', code: '+30' },
  { iso2: 'GD', country: 'Grenada', code: '+1' },
  { iso2: 'GT', country: 'Guatemala', code: '+502' },
  { iso2: 'GN', country: 'Guinea', code: '+224' },
  { iso2: 'GW', country: 'Guinea-Bissau', code: '+245' },
  { iso2: 'GY', country: 'Guyana', code: '+592' },
  { iso2: 'HT', country: 'Haiti', code: '+509' },
  { iso2: 'HN', country: 'Honduras', code: '+504' },
  { iso2: 'HU', country: 'Hungary', code: '+36' },
  { iso2: 'IS', country: 'Iceland', code: '+354' },
  { iso2: 'IN', country: 'India', code: '+91' },
  { iso2: 'ID', country: 'Indonesia', code: '+62' },
  { iso2: 'IR', country: 'Iran', code: '+98' },
  { iso2: 'IQ', country: 'Iraq', code: '+964' },
  { iso2: 'IE', country: 'Ireland', code: '+353' },
  { iso2: 'IL', country: 'Israel', code: '+972' },
  { iso2: 'IT', country: 'Italy', code: '+39' },
  { iso2: 'JM', country: 'Jamaica', code: '+1' },
  { iso2: 'JP', country: 'Japan', code: '+81' },
  { iso2: 'JO', country: 'Jordan', code: '+962' },
  { iso2: 'KZ', country: 'Kazakhstan', code: '+7' },
  { iso2: 'KE', country: 'Kenya', code: '+254' },
  { iso2: 'KI', country: 'Kiribati', code: '+686' },
  { iso2: 'KR', country: 'Korea, Republic of', code: '+82' },
  { iso2: 'KW', country: 'Kuwait', code: '+965' },
  { iso2: 'KG', country: 'Kyrgyzstan', code: '+996' },
  { iso2: 'LA', country: 'Laos', code: '+856' },
  { iso2: 'LV', country: 'Latvia', code: '+371' },
  { iso2: 'LB', country: 'Lebanon', code: '+961' },
  { iso2: 'LS', country: 'Lesotho', code: '+266' },
  { iso2: 'LR', country: 'Liberia', code: '+231' },
  { iso2: 'LY', country: 'Libya', code: '+218' },
  { iso2: 'LI', country: 'Liechtenstein', code: '+423' },
  { iso2: 'LT', country: 'Lithuania', code: '+370' },
  { iso2: 'LU', country: 'Luxembourg', code: '+352' },
  { iso2: 'MG', country: 'Madagascar', code: '+261' },
  { iso2: 'MW', country: 'Malawi', code: '+265' },
  { iso2: 'MY', country: 'Malaysia', code: '+60' },
  { iso2: 'MV', country: 'Maldives', code: '+960' },
  { iso2: 'ML', country: 'Mali', code: '+223' },
  { iso2: 'MT', country: 'Malta', code: '+356' },
  { iso2: 'MH', country: 'Marshall Islands', code: '+692' },
  { iso2: 'MR', country: 'Mauritania', code: '+222' },
  { iso2: 'MU', country: 'Mauritius', code: '+230' },
  { iso2: 'MX', country: 'Mexico', code: '+52' },
  { iso2: 'FM', country: 'Micronesia', code: '+691' },
  { iso2: 'MD', country: 'Moldova', code: '+373' },
  { iso2: 'MC', country: 'Monaco', code: '+377' },
  { iso2: 'MN', country: 'Mongolia', code: '+976' },
  { iso2: 'ME', country: 'Montenegro', code: '+382' },
  { iso2: 'MA', country: 'Morocco', code: '+212' },
  { iso2: 'MZ', country: 'Mozambique', code: '+258' },
  { iso2: 'MM', country: 'Myanmar', code: '+95' },
  { iso2: 'NA', country: 'Namibia', code: '+264' },
  { iso2: 'NR', country: 'Nauru', code: '+674' },
  { iso2: 'NP', country: 'Nepal', code: '+977' },
  { iso2: 'NL', country: 'Netherlands', code: '+31' },
  { iso2: 'NZ', country: 'New Zealand', code: '+64' },
  { iso2: 'NI', country: 'Nicaragua', code: '+505' },
  { iso2: 'NE', country: 'Niger', code: '+227' },
  { iso2: 'NG', country: 'Nigeria', code: '+234' },
  { iso2: 'MK', country: 'North Macedonia', code: '+389' },
  { iso2: 'NO', country: 'Norway', code: '+47' },
  { iso2: 'OM', country: 'Oman', code: '+968' },
  { iso2: 'PK', country: 'Pakistan', code: '+92' },
  { iso2: 'PW', country: 'Palau', code: '+680' },
  { iso2: 'PS', country: 'Palestine', code: '+970' },
  { iso2: 'PA', country: 'Panama', code: '+507' },
  { iso2: 'PG', country: 'Papua New Guinea', code: '+675' },
  { iso2: 'PY', country: 'Paraguay', code: '+595' },
  { iso2: 'PE', country: 'Peru', code: '+51' },
  { iso2: 'PH', country: 'Philippines', code: '+63' },
  { iso2: 'PL', country: 'Poland', code: '+48' },
  { iso2: 'PT', country: 'Portugal', code: '+351' },
  { iso2: 'QA', country: 'Qatar', code: '+974' },
  { iso2: 'RO', country: 'Romania', code: '+40' },
  { iso2: 'RU', country: 'Russia', code: '+7' },
  { iso2: 'RW', country: 'Rwanda', code: '+250' },
  { iso2: 'KN', country: 'Saint Kitts and Nevis', code: '+1' },
  { iso2: 'LC', country: 'Saint Lucia', code: '+1' },
  { iso2: 'VC', country: 'Saint Vincent and the Grenadines', code: '+1' },
  { iso2: 'WS', country: 'Samoa', code: '+685' },
  { iso2: 'SM', country: 'San Marino', code: '+378' },
  { iso2: 'ST', country: 'Sao Tome and Principe', code: '+239' },
  { iso2: 'SA', country: 'Saudi Arabia', code: '+966' },
  { iso2: 'SN', country: 'Senegal', code: '+221' },
  { iso2: 'RS', country: 'Serbia', code: '+381' },
  { iso2: 'SC', country: 'Seychelles', code: '+248' },
  { iso2: 'SL', country: 'Sierra Leone', code: '+232' },
  { iso2: 'SG', country: 'Singapore', code: '+65' },
  { iso2: 'SK', country: 'Slovakia', code: '+421' },
  { iso2: 'SI', country: 'Slovenia', code: '+386' },
  { iso2: 'SB', country: 'Solomon Islands', code: '+677' },
  { iso2: 'SO', country: 'Somalia', code: '+252' },
  { iso2: 'ZA', country: 'South Africa', code: '+27' },
  { iso2: 'SS', country: 'South Sudan', code: '+211' },
  { iso2: 'ES', country: 'Spain', code: '+34' },
  { iso2: 'LK', country: 'Sri Lanka', code: '+94' },
  { iso2: 'SD', country: 'Sudan', code: '+249' },
  { iso2: 'SR', country: 'Suriname', code: '+597' },
  { iso2: 'SE', country: 'Sweden', code: '+46' },
  { iso2: 'CH', country: 'Switzerland', code: '+41' },
  { iso2: 'SY', country: 'Syria', code: '+963' },
  { iso2: 'TW', country: 'Taiwan', code: '+886' },
  { iso2: 'TJ', country: 'Tajikistan', code: '+992' },
  { iso2: 'TZ', country: 'Tanzania', code: '+255' },
  { iso2: 'TH', country: 'Thailand', code: '+66' },
  { iso2: 'TL', country: 'Timor-Leste', code: '+670' },
  { iso2: 'TG', country: 'Togo', code: '+228' },
  { iso2: 'TO', country: 'Tonga', code: '+676' },
  { iso2: 'TT', country: 'Trinidad and Tobago', code: '+1' },
  { iso2: 'TN', country: 'Tunisia', code: '+216' },
  { iso2: 'TR', country: 'Turkey', code: '+90' },
  { iso2: 'TM', country: 'Turkmenistan', code: '+993' },
  { iso2: 'TV', country: 'Tuvalu', code: '+688' },
  { iso2: 'UG', country: 'Uganda', code: '+256' },
  { iso2: 'UA', country: 'Ukraine', code: '+380' },
  { iso2: 'AE', country: 'United Arab Emirates', code: '+971' },
  { iso2: 'GB', country: 'United Kingdom', code: '+44' },
  { iso2: 'US', country: 'United States', code: '+1' },
  { iso2: 'UY', country: 'Uruguay', code: '+598' },
  { iso2: 'UZ', country: 'Uzbekistan', code: '+998' },
  { iso2: 'VU', country: 'Vanuatu', code: '+678' },
  { iso2: 'VA', country: 'Vatican City', code: '+379' },
  { iso2: 'VE', country: 'Venezuela', code: '+58' },
  { iso2: 'VN', country: 'Vietnam', code: '+84' },
  { iso2: 'YE', country: 'Yemen', code: '+967' },
  { iso2: 'ZM', country: 'Zambia', code: '+260' },
  { iso2: 'ZW', country: 'Zimbabwe', code: '+263' },
  // Asia additions
  { iso2: 'HK', country: 'Hong Kong', code: '+852' },
  { iso2: 'MO', country: 'Macau', code: '+853' },
  // (deduped entries below already included above)
  // Oceania additions
  { iso2: 'PF', country: 'French Polynesia', code: '+689' },
  { iso2: 'NC', country: 'New Caledonia', code: '+687' },
];

export function isoToFlag(iso2: string) {
  if (!iso2 || iso2.length !== 2) return '';
  const codePoints = iso2
    .toUpperCase()
    .split('')
    .map((c) => 127397 + c.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}
